final fakeList = [
  " Pantallas 3D ",
  " Almacenamiento de datos ópticos en 3D ",
  " Impresión 3D ",
  " 3D-TV ",
  " Red celular 4G ",
  " Banda ancha 5G ",
  " actuadores ",
  " óptica adaptativa ",
  " Láseres tácticos avanzados ",
  " aerogeles ",
  " aeroscraft ",
  " medicina estética ",
  " robótica agrícola ",
  " ciencia agrícola ",
  " aerogeneradores aerotransportados ",
  " sistemas de control de vuelo de aeronaves ",
  " neumáticos sin aire ",
  " vehículos de combustible alternativo ",
  " aluminio ",
  " inteligencia ambiental ",
  " metales amorfos ",
  " electrónica analógica ",
  " Android ",
  " cría de animales ",
  " contestadores automáticos ",
  " Tecnología antigravedad ",
  " armas de antimateria ",
  " arcologías ",
  " cerebros artificiales ",
  " Sistemas de gravedad artificial ",
  " inteligencia artificial ",
  " Pasajeros artificiales ",
  " fotosíntesis artificial ",
  " minería de asteroides ",
  " eliminación de dióxido de carbono atmosférico ",
  " Atomtrónica ",
  " realidad aumentada ",
  " vehículos autoguiados ",
  " edificios autónomos ",
  " coches autónomos ",
  " robots de investigación autónomos ",
  " robótica autónoma ",
  " vehículos submarinos autónomos ",
  " pantallas autoestereoscópicas ",
  " helicópteros de mochila ",
  " banotecnología ",
  " códigos de barras ",
  " baterías ",
  " lavadoras de cuentas ",
  " propulsión de haz ",
  " robótica basada en el comportamiento ",
  " bioimpresión ",
  " BioLadrillos ",
  " biocombustibles ",
  " inmortalidad biológica ",
  " biometría ",
  " biomiméticos ",
  " lentes de contacto biónicos ",
  " bioplásticos ",
  " biorremediación ",
  " refugio biológico ",
  " Biosfera 2 ",
  " control de la natalidad ",
  " Bitcoin ",
  " Discos Blu-ray ",
  " implantes corporales ",
  " implantes cerebrales ",
  " trasplante de cerebro ",
  " interfaces cerebro-computadora ",
  " BrainGate ",
  " BrightSource Energy ",
  " banda ancha ",
  " cámaras ",
  " camuflaje ",
  " fibra de carbono ",
  " transistores de efecto de campo de nanotubos de carbono ",
  " nanotubos de carbono ",
  " combustibles neutros en carbono ",
  " munición sin vaina ",
  " catalizadores ",
  " chimeneas ",
  " cines ",
  " Claytronics ",
  " dispositivos de camuflaje ",
  " mantos de invisibilidad ",
  " sistemas ecológicos cerrados ",
  " robótica en la nube ",
  " revestimientos ",
  " implantes cocleares ",
  " radio cognitiva ",
  " cañones de bobina ",
  " colonización de la luna ",
  " materiales compuestos ",
  " vehículos de aire comprimido ",
  " interfaces de computadora ",
  " visión por computadora ",
  " holografía generada por computadora ",
  " imágenes generadas por computadora ",
  " energía solar concentrada ",
  " polímeros conductores ",
  " Elaboración de contornos ",
  " anticoncepción ",
  " sistemas de control ",
  " torres de enfriamiento ",
  " CPU ",
  " Pantallas CRT ",
  " criogenia ",
  " criónica ",
  " crioprotectores ",
  " criptomonedas ",
  " cyborgs ",
  " Forma de D ",
  " almacenamiento de datos ",
  " centros de datos ",
  " extinción ",
  "comunicaciones dedicadas de corto alcance ",
  " drones de reparto ",
  " foco de plasma denso ",
  " DESERTEC ",
  " bebés de diseño ",
  " monedas digitales ",
  " procesamiento de imágenes digitales ",
  " tecnología de aroma digital ",
  " armas de energía dirigida ",
  " informática distribuida ",
  " ciudades abovedadas ",
  " coches sin conductor ",
  " drones ",
  " hielo seco ",
  " e-democracia ",
  " e-learning ",
  " e-paper ",
  " e-textiles ",
  " coches eléctricos ",
  " condensadores eléctricos de doble capa ",
  " vehículos eléctricos ",
  " propulsión electrohidrodinámica ",
  " electroencefalografía ",
  " electrohidrodinámica ",
  " electroláseres ",
  " armas electromagnéticas ",
  " informática electrónica ",
  " contramedidas electrónicas ",
  " dispositivos electrónicos ",
  " electrónica ",
  " fluido electrorreológico ",
  " tecnología electrotérmica-química ",
  " recolección de energía ",
  " armas biológicas étnicas ",
  " Computación a exaescala ",
  " sistemas de lanzamiento fungibles ",
  " EyeTap ",
  " femtotecnología ",
  " Pantallas de líquido ferro ",
  " RAM ferroeléctrica ",
  " Pantallas de emisiones de campo ",
  " pesca ",
  " electrónica flexible ",
  " diodos emisores de luz orgánicos flexibles ",
  " controles de vuelo fluidos ",
  " coches voladores ",
  " almacenamiento de energía en el volante ",
  " volantes ",
  " campos de fuerza ",
  " combustibles fósiles ",
  " discos ópticos de cuarta generación ",
  " secuenciación del genoma completo ",
  " fullereno ",
  " energía de fusión ",
  " cohetes de fusión ",
  " reciclaje de antorchas de fusión ",
  " dopaje genético ",
  " terapia génica ",
  " reactores de generación IV ",
  " ingeniería genética ",
  " alimentos modificados genéticamente ",
  " domos geodésicos ",
  " vaso ",
  " GNU Radio ",
  " Google Glass ",
  " grafeno ",
  " unidades de procesamiento de gráficos ",
  " campos gravitomagnéticos ",
  " balas verdes ",
  " invernaderos ",
  " almacenamiento de energía de la red ",
  " trenes de efecto suelo ",
  " ginoide ",
  " giroscopios ",
  " trasplante de mano ",
  " trajes hápticos ",
  " unidades de disco duro ",
  " pantallas montadas en la cabeza ",
  " pantallas de visualización ",
  " disipadores de calor ",
  " Plataformas de gran altitud ",
  " superconductividad de alta temperatura ",
  " acumuladores de gran capacidad ",
  " superconductividad de alta temperatura ",
  " superfluidez a alta temperatura ",
  " almacenamiento de datos holográficos ",
  " pantallas holográficas ",
  " TV holográfica ",
  " holografía ",
  " pilas de combustible domésticas ",
  " hoverboards ",
  " aerodeslizador ",
  " mejora humana ",
  " interacción humano-computadora ",
  " vehículos de hidrógeno ",
  " aleaciones hipereutécticas ",
  " Pistones hipereutécticos ",
  " Hyperloop ",
  " transporte hipersónico ",
  " Espectro IEEE 802.16m ",
  " iGEM ",
  " Realidad virtual inmersiva ",
  " carne in vitro ",
  " incubadoras ",
  " agricultura industrial ",
  " hábitat espacial inflable ",
  " implantes de bomba de insulina ",
  " circuitos integrados ",
  " entornos inteligentes ",
  " sistemas de transporte inteligentes ",
  " televisión interactiva ",
  " visualización del modulador interferométrico ",
  " viaje interestelar ",
  " propulsores de iones ",
  " Huele ",
  " Tejido jacquard ",
  " motores a reacción ",
  " mochilas propulsoras ",
  " kevlar ",
  " KiteGen ",
  " propulsión láser ",
  " televisores láser ",
  " pantallas de vídeo láser ",
  " Sistemas de armas láser ",
  " armas láser ",
  " Pantallas LCD ",
  " Li-Fi ",
  " extensión de vida ",
  " pantallas de campo de luz ",
  " Tecnologías ligeras de armas pequeñas ",
  " Baterías de fosfato de hierro y litio ",
  " Baterías de litio-aire ",
  " Baterías de iones de litio ",
  " Baterías de litio-azufre ",
  " LiTraCon ",
  " logística ",
  " Red celular avanzada LTE ",
  " traducción automática ",
  " visión artificial ",
  " Trenes maglev ",
  " levitación magnética ",
  " refrigeración magnética ",
  " almacenamiento de datos en cinta magnética ",
  " memoria magnetorresistiva de acceso aleatorio ",
  " amortiguador magnetorreológico ",
  " fluido magnetorreológico ",
  " anticoncepción masculina ",
  " conductores de masas ",
  " tricorders médicos ",
  " memristores ",
  " redes de malla ",
  " espuma de metal ",
  " encubrimiento de metamateriales ",
  " metamateriales ",
  " microvehículos aéreos ",
  " microscopios ",
  " memoria de milpiés ",
  " carga mental ",
  " satélites miniaturizados ",
  " defensa antimisiles ",
  " banda ancha móvil ",
  " colaboración móvil ",
  " TV móvil ",
  " ensambladores moleculares ",
  " electrónica molecular ",
  " nanotecnología molecular ",
  " baterías de sal fundida ",
  " reactores de sales fundidas ",
  " películas ",
  " MRAM ",
  " Escáneres de resonancia magnética ",
  " sistemas multiagente ",
  " estructuras multifunción ",
  " fusión catalizada por muones ",
  " sistemas nanoelectromecánicos ",
  " nanomateriales ",
  " nanomedicinas ",
  " nanorobótica ",
  " nanosensores ",
  " baterías de nanocables ",
  " nantennas ",
  " redes neuronales ",
  " neuroinformática ",
  " neuroprótesis ",
  " nootrópicos ",
  " NRAM ",
  " energía de fisión nuclear ",
  " propulsión nuclear por pulsos ",
  " conversión de energía térmica oceánica ",
  " consumo de aceite ",
  " Pantallas OLED ",
  " Virus oncolíticos ",
  " datos abiertos ",
  " computación óptica ",
  " almacenamiento de datos ópticos ",
  " almacenamiento óptico ",
  " óptica ",
  " impresión de órganos ",
  " trasplante de órganos ",
  " transistores emisores de luz orgánicos ",
  " células solares orgánicas ",
  " marcapasos ",
  " parálisis ",
  " armas de haz de partículas ",
  " optimización del enjambre de partículas ",
  " casas pasivas ",
  " reconocimiento de patrones ",
  " genómica personal ",
  " tránsito rápido personal ",
  " medicina personalizada ",
  " informática generalizada ",
  " memoria de cambio de fase ",
  " óptica de matriz en fase ",
  " energía fotovoltaica ",
  " picotecnología ",
  " mejoramiento de plantas y hongos ",
  " plantibodies ",
  " sigilo de plasma ",
  " armas de plasma ",
  " ventanas de plasma ",
  " exoesqueletos motorizados ",
  " agricultura de precisión ",
  " lógica programable ",
  " materia programable ",
  " celdas de metalización programables ",
  " prótesis ",
  " prótesis ",
  " armas de fusión pura ",
  " cuadricópteros ",
  " relojes cuánticos ",
  " computación cuántica ",
  " criptografía cuántica ",
  " visualización de puntos cuánticos ",
  " láseres de puntos cuánticos ",
  " puntos cuánticos ",
  " memoria de pista ",
  " material absorbente de radar ",
  " cañones de riel ",
  " creación rápida de prototipos ",
  " informática reconfigurable ",
  " frenado regenerativo ",
  " medicina regenerativa ",
  " energía renovable ",
  " Reprogenética ",
  " investigación en ciencias naturales ",
  " acoplamiento inductivo resonante ",
  " implantes de retina ",
  " sistemas de lanzamiento reutilizables ",
  " ReWalk ",
  " Filtros de RF y microondas ",
  " RFID ",
  " cirugía robótica ",
  " robots ",
  " procreación entre personas del mismo sexo ",
  " visualizaciones sin pantalla ",
  " invernaderos de agua de mar ",
  " material de autocuración ",
  " autopago ",
  " robots modulares autoconfigurables ",
  " Servicios web semánticos ",
  " Tren maglev de Shanghai ",
  " amortiguadores ",
  " procesamiento de señales ",
  " Silicene ",
  " Batería de silicio-aire ",
  " realidad simulada ",
  " pistolas de células cutáneas ",
  " Sky Hook ",
  " Skyrmion ",
  " ciudades inteligentes ",
  " contadores inteligentes ",
  " lentes inteligentes ",
  " smartphones ",
  " tiendas inteligentes ",
  " Olor-O-Visión ",
  " antena definida por software ",
  " radio definida por software ",
  " células solares ",
  " carreteras solares ",
  " velas solares ",
  " torre de corriente ascendente solar ",
  " armas sónicas ",
  " colonias espaciales ",
  " colonización espacial ",
  " ascensores espaciales ",
  " fuentes espaciales ",
  " viaje espacial ",
  " energía solar basada en el espacio ",
  " aviones espaciales ",
  " Programa de desarrollo del sistema de lanzamiento reutilizable de SpaceX ",
  " reconocimiento de voz ",
  " Espintrónica ",
  " Replicadores de Star Trek ",
  " avión furtivo ",
  " tecnología sigilosa ",
  " acero ",
  " tratamientos con células madre ",
  " pantallas estereoscópicas ",
  " Estrategias para la senescencia insignificante diseñada ",
  " reconocimiento subvocal ",
  " aleaciones superplásticas ",
  " superaleaciones ",
  " supercomputadoras ",
  " superfluidez ",
  " superplasticidad ",
  " transporte supersónico ",
  " anestesia quirúrgica ",
  " animación suspendida ",
  " inteligencia de enjambre ",
  " robótica de enjambre ",
  " pantallas de volumen barrido ",
  " biología sintética ",
  " diamante sintético ",
  " genómica sintética ",
  " T-RAM ",
  " Talimogene laherparepvec ",
  " pantallas de píxeles telescópicas ",
  " televisión ",
  " Teletrabajo ",
  " terraformación ",
  " el ala adaptable compatible ",
  " el Aérotrain ",
  " el AeroVironment Global Observer ",
  " el AeroVironment Nano Hummingbird ",
  " el útero artificial ",
  " el automóvil ",
  " el demonio de BAE Systems ",
  " el servidor de energía Bloom ",
  " el Proyecto Cerebro Azul ",
  " el CityCar ",
  " el Concorde ",
  " la Web Semántica Corporativa ",
  " el PRT del Hospital Duke ",
  " El Proyecto Edén ",
  " el coche eléctrico ",
  " la red eléctrica ",
  " la nariz electrónica ",
  " la Puerta de Europa ",
  " el coche sin conductor de Google ",
  " el sistema de defensa de área de láser líquido de alta energía ",
  " la holocubierta ",
  " el Hovertrain ",
  " el HTC Evo 3D ",
  " el Proyecto del Cerebro Humano ",
  " el portador de carga universal humano ",
  " la economía del hidrógeno ",
  " los hipertelescopios ",
  " el motor de combustión interna ",
  " Internet de las cosas ",
  " el exoesqueleto de LOPES ",
  " el coche del MIT ",
  " el Skycar Moller M400 ",
  " la Nintendo 3DS ",
  " el Nokia Morph ",
  " Oculus Rift ",
  " la Internet física ",
  " el motor de detonación de pulsos ",
  " el Proyecto RepRap ",
  " el Scramjet ",
  " la pila de Web semántica ",
  " la Web Semántica ",
  " la red inteligente ",
  " el chaleco espacial ",
  " la SuperSmart Grid ",
  " la singularidad tecnológica ",
  " el ciclo del combustible de torio ",
  " el Tweel ",
  " la especificación de periféricos de radio de software universal ",
  " el X-Hawk de Urban Aeronautics ",
  " el Vactrain ",
  " El desafío de la Tierra Virgen ",
  " la Virtusfera ",
  " la pistola de anillo Vortex ",
  " la rueda ",
  " protuberancias térmicas de pilares de cobre ",
  " generación de energía termoeléctrica ",
  " circuitos integrados tridimensionales ",
  " obturadores ópticos multiplexados en el tiempo ",
  " neumáticos ",
  " ingeniería de tejidos ",
  " regeneración dental ",
  " transhumanismo ",
  " tricorders ",
  " Tupolev Tu-144 ",
  " discos holográficos de ultra alta definición ",
  " vehículos aéreos no tripulados ",
  " vehículos aéreos de combate no tripulados ",
  " vehículos terrestres no tripulados ",
  " vehículos espaciales no tripulados ",
  " vehículos de superficie no tripulados ",
  " vehículos submarinos no tripulados ",
  " vehículos no tripulados ",
  " nieblas de utilidad ",
  " V-tex ",
  " agricultura vertical ",
  " videojuegos ",
  " videos virales ",
  " viroterapia ",
  " realidad virtual ",
  " visualizaciones retinianas virtuales ",
  " prótesis visuales ",
  " vitrificación ",
  " pantallas volumétricas ",
  " Constructores universales de Von Neumann ",
  " Motores de vórtice ",
  " lavadoras ",
  " ordenadores portátiles ",
  " Web 2.0 ",
  " Web 3.0 ",
  " Windows Holográfico ",
  " transferencia de energía inalámbrica ",
  " armas de descarga eléctrica inalámbrica de largo alcance ",
  " WiTricity ",
  " Máquinas de rayos X ",
  " edificios de energía cero "
];
